### ISSUE TITLE
[M0 - Dev] Elección del lenguaje de programación.

### ISSUE THREAD

**Issue by joseantonio2001** [martahuetem/IV_HorseMatch#8]
Se va a determinar que tecnología utilizar para el proyecto.
Información referente en el archivo iv.yaml

Como lenguaje de programación se ha seleccionado **node.js**.

**Comment by martahuetem** [comment]
Hola @joseantonio2001! 
Pues estaba entre Ruby y node.js que creo que ambos se podrían adaptar bien a mi proyecto. ¿Tienes tu preferencia por alguno?

**Comment by joseantonio2001** [comment]
> Hola @joseantonio2001! Pues estaba entre Ruby y node.js que creo que ambos se podrían adaptar bien a mi proyecto. ¿Tienes tu preferencia por alguno?

Pues no tengo preferencia en principio, puedo amoldarme al lenguaje al que tengas más experiencia o te resulte más cómodo de los dos.

**Comment by joseantonio2001** [comment]
He estado desarrollando un poco las clases del proyecto y he usado el lenguaje **node.js**.

**Comment by martahuetem** [comment]
Vale, perfecto!! 😁
